data_cfg:
  dataset_name: DataSet_LTGait_full
  dataset_root: 
    # silhouette_root: /public/home/dongyl/Gait3D-Benchmark/Gait3D-sils-64-44-pkl
    # smpl_root: /public/home/dongyl/Gait3D-Benchmark/Gait3D-smpls-pkl
    # smpl_sil_root: /public/home/dongyl/Gait3D-Benchmark/Gait3D-smpls-sil-cropped_64_44_pkl
    silhouette_root: /public/home/dongyl/Gait3D-Benchmark/CCGait_sil_pkl
    smpl_root: /public/home/dongyl/Gait3D-Benchmark/CCGait_smpl_pkl
    smpl_sil_root: /public/home/dongyl/Gait3D-Benchmark/CCGait_smpl_sil_0_pkl
  dataset_partition: /public/home/dongyl/Gait3D-Benchmark/misc/partitions/ccgait_sil.json
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: /public/home/dongyl/Gait3D-Benchmark/DataSet_LTGait_full

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 35000
  save_name: HybridGait
  eval_func: evaluation_LTGait
  sampler:
    # plus_smpl: False
    plus_smpl: True
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
    frames_skip_num: 2
    two_types_sample: True
    two_types_format: smpl_sil_smpl
    two_time_stream: False
    with_sil: True
  metric: cos # cos euc
  transform:
    - type: BaseSilTransform
  transform_smpl_sil:
    - type: SmplSilTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: HybridGait
  backbone_cfg:
    in_channels:
    - 1
    - 64
    - 128
    - 256
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SeparateBNNecks:
    class_num: 3000
    in_channels: 256
    parts_num: 31
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1
  temporal:
    bind_frame_num: 3
    frames_num_fixed: 30

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 10000
    - 30000
    - 50000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: HybridGait
  sync_BN: true
  total_iter: 180000
  sampler:
    plus_smpl: True
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4  #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    frames_skip_num: 2
    two_types_sample: True
    two_types_format: smpl_sil_smpl
    two_time_stream: False
    with_sil: True
    type: TripletSampler
  transform:
    - type: BaseSilTransform
  transform_smpl_sil:
    - type: SmplSilTransform
